
FAIL navigate() with unserializable state in a detached iframe throws "DataCloneError", not "InvalidStateError" assert_throws_dom: function "() => { throw committedReason; }" threw object "InvalidStateError: Invalid state" that is not a DOMException DataCloneError: property "code" is equal to 11, expected 25

