
FAIL navigate() with an invalid URL in a detached iframe throws "SyntaxError", not "InvalidStateError" assert_throws_dom: function "() => { throw committedReason; }" threw object "InvalidStateError: Invalid state" that is not a DOMException SyntaxError: property "code" is equal to 11, expected 12

